version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  directus:
    image: directus/directus:latest
    depends_on:
      - postgres
      - redis
    environment:
      KEY: "CHANGE_THIS_KEY"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password"
      DATABASE_CLIENT: "pg"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: 5432
      DATABASE_DATABASE: "directus"
      DATABASE_USER: "directus"
      DATABASE_PASSWORD: "directus"
      REDIS_HOST: "redis"
    ports:
      - "8055:8055"
    restart: always

  api:
    build:
      context: ./api
    depends_on:
      - redis
      - postgres
    environment:
      PORT: 8080
      REDIS_ADDR: "redis:6379"
    ports:
      - "8080:8080"
    # 若需 ICMP 权限，可在部署时开启 NET_RAW 能力（仅在可控环境）
    # cap_add:
    #   - NET_RAW

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
      - directus

volumes:
  pgdata:
